# Generated by Django 2.1.7 on 2019-03-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
